-- Club Manager: Foundation
--
-- APPLIED to the shared Dula HQ Supabase project (zytyakbgwaegvftblkcn)
-- as migration version 20260820032053. This file is a mirror of what
-- was actually run via the Supabase MCP `apply_migration` tool -- it
-- exists so `supabase db push` recognizes this as already-applied
-- history rather than something new to push. Do not edit this file's
-- SQL after the fact without also reconciling the live database.
--
-- Purely additive to the existing Dula HQ schema. Does NOT create
-- tenants/tenant_users/organizations/sports/audit_logs -- none of that
-- exists in this database and none of it is introduced here.
--
-- Identity model: this schema resolves the current user via
-- `auth.jwt() ->> 'email'` matched against public.users.email (see the
-- existing current_user_role()/current_user_team_ids() functions) --
-- NOT via auth.uid() = public.users.id, since no such relationship
-- exists. current_dula_user_id() below is the shared helper for that
-- lookup, reused by every Club Manager function that follows.

create or replace function current_dula_user_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id from public.users where email = auth.jwt() ->> 'email' limit 1;
$$;

-- ---------------------------------------------------------------------
-- clubs: deliberately no tenant_id -- no tenant system exists here.
-- ---------------------------------------------------------------------
create table if not exists public.clubs (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  branding jsonb not null default '{}'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.users(id)
);

-- ---------------------------------------------------------------------
-- club_staff: club-scoped roles. user_id references public.users(id)
-- (not auth.users) -- club staff are existing Dula HQ people (coaches,
-- admins) identified the same way the rest of the app identifies them.
-- ---------------------------------------------------------------------
create table if not exists public.club_staff (
  id uuid primary key default gen_random_uuid(),
  club_id uuid not null references public.clubs(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  role text not null check (role in ('club_admin', 'staff', 'coach', 'team_manager')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references public.users(id),
  unique (club_id, user_id, role)
);

create index if not exists idx_club_staff_club_id on public.club_staff(club_id);
create index if not exists idx_club_staff_user_id on public.club_staff(user_id);

-- ---------------------------------------------------------------------
-- teams.club_id: nullable, on delete set null. A team without a club
-- association remains fully valid for Tournament Manager -- this column
-- is purely additive and optional.
-- ---------------------------------------------------------------------
alter table public.teams
  add column if not exists club_id uuid references public.clubs(id) on delete set null;

create index if not exists idx_teams_club_id on public.teams(club_id);
